import jsPDF from 'jspdf'

export function downloadPDF(result) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20 // current Y position on page

  // ===== Helper functions =====
  const addLine = (text, size = 12, color = [245, 245, 245], bold = false) => {
    doc.setFontSize(size)
    doc.setTextColor(...color)
    if (bold) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    doc.text(text, 20, y)
    y += size * 0.6
  }

  const addGap = (gap = 8) => { y += gap }

  const addDivider = () => {
    doc.setDrawColor(0, 206, 209)
    doc.line(20, y, pageWidth - 20, y)
    y += 8
  }

  const checkNewPage = () => {
    if (y > 270) { doc.addPage(); y = 20 }
  }

  // ===== Background =====
  doc.setFillColor(6, 9, 16)
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F')

  // ===== Header =====
  addLine('BUILDIT', 28, [0, 206, 209], true)
  addLine('AI Startup Validation Report', 12, [192, 192, 192])
  addGap(4)
  addLine(`Idea: ${result.title}`, 14, [245, 245, 245], true)
  addLine(`Date: ${result.date}`, 10, [192, 192, 192])
  addGap(4)
  addDivider()

  // ===== Summary =====
  addLine('IDEA SUMMARY', 10, [0, 206, 209], true)
  addGap(4)
  addLine(`Industry: ${result.summary.industry}`, 11, [245, 245, 245])
  addGap(3)
  addLine(`Target Audience: ${result.summary.targetAudience}`, 11, [245, 245, 245])
  addGap(3)
  addLine(`Stage: ${result.stage}`, 11, [245, 245, 245])
  addGap(8)
  addDivider()

  // ===== Scores =====
  addLine('BUILDIT SCORE', 10, [0, 206, 209], true)
  addGap(4)
  addLine(`Overall Score: ${result.buildItScore} / 100`, 20, [245, 245, 245], true)
  addGap(3)
  addLine(`Risk Level: ${result.riskLevel}`, 12, [245, 245, 245])
  addGap(8)

  // ===== Category Scores =====
  addLine('CATEGORY SCORES', 10, [0, 206, 209], true)
  addGap(4)
  addLine(`Market Opportunity:     ${result.categoryScores.marketOpportunity} / 10`, 11, [245, 245, 245])
  addGap(3)
  addLine(`Competition Level:      ${result.categoryScores.competitionLevel} / 10`, 11, [245, 245, 245])
  addGap(3)
  addLine(`Feasibility:            ${result.categoryScores.feasibility} / 10`, 11, [245, 245, 245])
  addGap(3)
  addLine(`Monetization Potential: ${result.categoryScores.monetizationPotential} / 10`, 11, [245, 245, 245])
  addGap(8)
  addDivider()
  checkNewPage()

  // ===== Competitors =====
  addLine('COMPETITOR ANALYSIS', 10, [0, 206, 209], true)
  addGap(4)
  result.competitors.forEach((comp, i) => {
    addLine(`${i + 1}. ${comp.name}`, 11, [245, 245, 245], true)
    addGap(2)
    const descLines = doc.splitTextToSize(comp.description, pageWidth - 40)
    doc.setFontSize(10)
    doc.setTextColor(192, 192, 192)
    doc.text(descLines, 20, y)
    y += descLines.length * 6
    addGap(4)
    checkNewPage()
  })
  addDivider()

  // ===== Risks =====
  addLine('TOP RISKS', 10, [255, 77, 77], true)
  addGap(4)
  result.risks.forEach((risk, i) => {
    const lines = doc.splitTextToSize(`${i + 1}. ${risk}`, pageWidth - 40)
    doc.setFontSize(11)
    doc.setTextColor(245, 245, 245)
    doc.text(lines, 20, y)
    y += lines.length * 6 + 4
    checkNewPage()
  })
  addGap(4)

  // ===== Opportunities =====
  addLine('OPPORTUNITIES', 10, [0, 200, 150], true)
  addGap(4)
  result.opportunities.forEach((opp, i) => {
    const lines = doc.splitTextToSize(`${i + 1}. ${opp}`, pageWidth - 40)
    doc.setFontSize(11)
    doc.setTextColor(245, 245, 245)
    doc.text(lines, 20, y)
    y += lines.length * 6 + 4
    checkNewPage()
  })
  addDivider()

  // ===== Verdict =====
  addLine('FINAL VERDICT', 10, [0, 206, 209], true)
  addGap(4)
  const verdictLines = doc.splitTextToSize(result.verdict, pageWidth - 40)
  doc.setFontSize(11)
  doc.setTextColor(245, 245, 245)
  doc.text(verdictLines, 20, y)
  y += verdictLines.length * 6
  addGap(10)

  // ===== Footer =====
  addLine('Generated by Buildit — buildit.vercel.app', 9, [100, 100, 100])

  // ===== Save =====
  doc.save(`buildit-report-${result.title.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}